#-------------------------------
# Site Settings
title: Jacob Stambaugh
logo: # You can add own logo. For example '/images/logo.png'.
author: Jacob Stambaugh
description: A portfolio site to showcase some of my work/art.

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'

#-------------------------------
# Hero Settings
hero:
  hero__title: Hello, I'm Jacob Stambaugh, a Data Scientist/Engineer living in Austin, Texas.
  hero__description: I am a passionate Data scientist, who has spent the past few years defining & visualizing complex problems in various domains. From healthcare & biotech to finance & real estate to ecology & biology, I have been solving problems and learning new prospectives and skills to carry with me as I continue to challenge the norms of these spaces. I invite you to navigate my portfolio and learn more about me and my work.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Visualization Portfolio
  portfolio__gallery:
    - image: /images/gallery-01.jpg
      title: Samantha Gades
      description: Brown photo frame beside wall <a href="https://unsplash.com/photos/8Od75hgzb9Y">Unsplash</a>

    - image: /images/gallery-02.jpg
      title: Paula Vermeulen
      description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

    - image: /images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/gallery-04.jpg
      title: Nord Wood
      description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

    - image: /images/gallery-05.jpg
      title: Luca Bravo
      description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    - image: /images/gallery-06.jpg
      title: Isaac Benhesed
      description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    - image: /images/gallery-07.jpg
      title: Water Journal
      description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    - image: /images/gallery-08.jpg
      title: Luca Bravo
      description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    - image: /images/gallery-09.jpg
      title: Books and Laptop
      description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-pinterest", color: "#bd081c", label: Kaggle, link: "https://www.kaggle.com/jacobstambaugh"}
- {icon: "ion-logo-dribbble", color: "#ea4c89", label: Medium, link: "https://medium.com/@jstambaugh00"}
- {icon: "ion-logo-github", color: "#24292e", label: Github, link: "https://github.com/Jstambaugh00"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: jstambaugh00@gmail.com # Add your email for contact form
  description:  Feel free to reach out with any business inquiries

#-------------------------------
# Google Analytics
google-analytics: G-7DXXL3Q56P # Add your identifier. For example UA-99631805-1.
